apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.nginx.ingress.enabled }}
  APP_URL: "http://{{ .Values.nginx.ingress.hostname }}/"
  {{- else }}
  APP_URL: "http://{{ include "common.names.fullname" . }}/"
  {{- end }}
  APP_DEBUG: {{ .Values.debug | quote }}
  DB_HOST1: {{ include "invoiceninja.databaseHost" . | quote }}
  DB_PORT1: {{ include "invoiceninja.databasePort" . | quote }}
  DB_USERNAME1: {{ include "invoiceninja.databaseUser" . | quote }}
  DB_DATABASE1: {{ include "invoiceninja.databaseName" . | quote }}
  {{- if not (empty .Values.logChannel) }}
  LOG_CHANNEL: {{ .Values.logChannel | quote }}
  {{- end }}
  {{- if not (empty .Values.broadcastDriver) }}
  BROADCAST_DRIVER: {{ .Values.broadcastDriver | quote }}
  {{- else if or .Values.redis.enabled (not (empty .Values.externalRedis.host)) }}
  BROADCAST_DRIVER: redis
  {{- end }}
  {{- if not (empty .Values.cacheDriver) }}
  CACHE_DRIVER: {{ .Values.cacheDriver | quote }}
  {{- else if or .Values.redis.enabled (not (empty .Values.externalRedis.host)) }}
  CACHE_DRIVER: redis
  {{- end }}
  {{- if not (empty .Values.sessionDriver) }}
  SESSION_DRIVER: {{ .Values.sessionDriver | quote }}
  {{- else if or .Values.redis.enabled (not (empty .Values.externalRedis.host)) }}
  SESSION_DRIVER: redis
  {{- end }}
  {{- if not (empty .Values.queueConnection) }}
  QUEUE_CONNECTION: {{ .Values.queueConnection | quote }}
  {{- else if or .Values.redis.enabled (not (empty .Values.externalRedis.host)) }}
  QUEUE_CONNECTION: redis
  {{- end }}
  PHANTOMJS_PDF_GENERATION: {{ not .Values.snappdf | quote}}
  REDIS_HOST: {{ include "invoiceninja.redisHost" . | quote }}
  REDIS_PORT: {{ include "invoiceninja.redisPort" . | quote }}
  REDIS_DB: {{ include "invoiceninja.redisDatabase" . | quote }}
  REDIS_CACHE_DB: {{ include "invoiceninja.redisCacheDatabase" . | quote }}
